---

- hosts: all
  become: true
  tasks:
  
  - name: update respositories
    apt:
      update_cache: yes

  - name: install the apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
